version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test_nest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - test-nest

volumes:
  postgres_data:

networks:
  test-nest:
    driver: bridge 